name: ci

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io1
          repository: pjstaab/osmseed-osm-processor
          tag_with_ref: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
